### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by amanuel1995** [amanuel1995/MI-449-SS17-741-js-conditionals-uMDt4P#1]
@stuartpearman Can you take a look at this? It's [hosted here](https://amanuel1995.github.io/MI-449-SS17-741-js-conditionals-uMDt4P/) and meets the following criteria:

- [x] Use the `prompt` and `confirm` functions (each at least once) to collect choices from the user (the entire story will take place in dialog boxes, so your `body` element could actually be empty, apart from the `script` element to include your JavaScript)
- [x] Use `if`, `else if`, and `else` to branch the story, based on user choices
- [x] In at least one branch, there should be at least 3 choices for the user to make
- [x] Include at least one branch where different things can happen each time with `Math.random()`
- [x] Use a logical operator (`&&` or `||`) at least once, where it makes sense
- [x] It should be impossible for an error to ever occur when playing your game, including handling for `null`/`undefined` where appropriate
- [x] All string input should be normalized, so that extra whitespace or a letter that's the wrong case will never cause a failed match
- [x] At least one number value is collected and used in a comparison (don't forget to convert it into a number first)
- [x] Don't get _too_ carried away -- it can be tempting to build a complex video game, but remember, you can always come back and build on this project later

**Comment by stuartpearman** [comment]
Hey Amanuel, I have some changes for you. It'll be easiest to jot them down when you come into class later.

**Comment by stuartpearman** [comment]
- Put story narrative in `prompts`

**Comment by amanuel1995** [comment]
Done!

**Comment by stuartpearman** [comment]
This is good! The only thing I will say is that the `Math.random()` function only affects when you press the cancel button, which isn't really a part of the game. But it seems you understand everything, so I will ship it through! :shipit: :+1:

**Comment by amanuel1995** [comment]
Yes I did understand it all. Thank you for pointing that out. I was also thinking the same but I thought I would focus on catching up on other lessons than just spend time doing what I already know. Thanks, again.
